<a href="https://colab.research.google.com/github/dmontillao/ciencia-datos-curso/blob/main/tarea_02_pandas_ingestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


Parte 1 — Cargar y explorar datos

In [4]:
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv'
df = pd.read_csv(url)

P2. Muestra las primeras 5 filas del DataFrame.

In [5]:
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

P3. Usa .info() para ver los tipos de columnas y si hay valores nulos.
Luego usa .describe() para ver el resumen estadístico. ¿Cuántas filas tiene el dataset?

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [7]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


Parte 2 — Selección y filtrado

P4. Selecciona solo las columnas sepal_length y species e imprime las primeras 5 filas.

In [9]:
df[['sepal_length', 'species']].head(5)

   sepal_length species
0           5.1  setosa
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa

P5. Filtra el DataFrame para quedarte solo con las flores de la especie virginica.
¿Cuántas filas tiene ese subconjunto?

In [13]:
df['species'][df['species']=='virginica']

100    virginica
101    virginica
102    virginica
103    virginica
104    virginica
105    virginica
106    virginica
107    virginica
108    virginica
109    virginica
110    virginica
111    virginica
112    virginica
113    virginica
114    virginica
115    virginica
116    virginica
117    virginica
118    virginica
119    virginica
120    virginica
121    virginica
122    virginica
123    virginica
124    virginica
125    virginica
126    virginica
127    virginica
128    virginica
129    virginica
130    virginica
131    virginica
132    virginica
133    virginica
134    virginica
135    virginica
136    virginica
137    virginica
138    virginica
139    virginica
140    virginica
141    virginica
142    virginica
143    virginica
144    virginica
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, dtype: object

P6. Filtra las filas donde petal_length sea mayor a 5.0. Imprime cuántas filas cumplen esa condición.

In [14]:
df['petal_length'][df['petal_length']> 5.0]

83     5.1
100    6.0
101    5.1
102    5.9
103    5.6
104    5.8
105    6.6
107    6.3
108    5.8
109    6.1
110    5.1
111    5.3
112    5.5
114    5.1
115    5.3
116    5.5
117    6.7
118    6.9
120    5.7
122    6.7
124    5.7
125    6.0
128    5.6
129    5.8
130    6.1
131    6.4
132    5.6
133    5.1
134    5.6
135    6.1
136    5.6
137    5.5
139    5.4
140    5.6
141    5.1
142    5.1
143    5.9
144    5.7
145    5.2
147    5.2
148    5.4
149    5.1
Name: petal_length, dtype: float64


Parte 3 — Guardar datos

In [18]:
import os
if not os.path.exists('output'):
    os.makedirs('output')

# Guardamos el dataframe filtrado
# index=False evita que se guarde la columna de índices automáticos de pandas
df.to_csv('output/solo_virginica.csv', index=False)
print("Archivo guardado en output/solo_virginica.csv")

Archivo guardado en output/solo_virginica.csv

P8. Carga de nuevo el archivo output/virginica.csv y verifica que tiene el número correcto de filas usando .shape.

In [20]:
df = pd.read_csv('output/solo_virginica.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
df.shape

(150, 5)